### ISSUE TITLE
Vary By Named Querystring Params or Http Headers

### ISSUE THREAD

**Issue by phil000** [filipw/Strathweb.CacheOutput#188]
Hi,
Traditionally MVC http output cache can be varied by a specified set of (semicolon separated) values in http header, or querystring. 

Is there any support for that as it was a very useful feature, especially if your API can return different content types based on Accept, can be compressed by Accept-Encoding, is multi-tenanted and your tenantId is itself an http header, etc.

From looking at the code it seems not, just a wrapper over System.Net.Http CacheControlHeaderValue which is very weak sauce from MS.

I see _maybe_ expected content type is specifically catered for in `MakeCacheKey(..)`, but not encoding, or language, or any other specified http header.

If there's no ability to vary by specifically named http header I think maybe you should add support for a few common ones, like Accept-Language, Accept-Encoding,

Varying by _all_ querystring or not at all works ok.

**Comment by ebergstedt** [comment]
In makecachekey, isn't the httpcontext request there? can't you see headers in that?

**Comment by phil000** [comment]
Hello,
We weren't planning on _changing_ the code, only trying to assess the libraries current capabilities in terms of support for varying cache results by named http headers and querystring parameters. I believe we have out answer anyway.

**Comment by ebergstedt** [comment]
If you have your answer, consider writing it down here for the people who will find this topic on google looking for answers.

**Comment by stevenrobijns** [comment]
For those interested, here's a code sample for a similar use case described by @phil000 
Here the server keeps cache per user (because the response for the request is based on the user's rights)
`
    public class UniqueCacheKeyByUserGenerator : DefaultCacheKeyGenerator
    {
        public override string MakeCacheKey(HttpActionContext context, MediaTypeHeaderValue mediaType, bool excludeQueryString = false)
        {
            var result = base.MakeCacheKey(context, mediaType, excludeQueryString);
            result += ((IMyrApplicationPrincipal) context.RequestContext.Principal).User.Id;
            return result;
        }
    }
`

If you want to do it based on a specific request header you can access it through context.Request.Headers.

Though it worked I removed thise code and eventually chose for the client caching only. It made more sense in my case, so considering doing it as well. (+ keep in mind the more unique cache keys you have the bigger your server cache gets)
