### ISSUE TITLE
InvalidateCacheOutput attribute on POST operations invalidates all cache entries instead of just the updated ones

### ISSUE THREAD

**Issue by johnib** [filipw/Strathweb.CacheOutput#214]
Hey,

Given a controller with the following two APIs:

```C#
[CacheOutput(ServerTimeSpan = 6000)]
[AcceptVerbs("GET")]
[Route("api/values/{valueId}")]
public async Task<IHttpActionResult> GetValueEntity(
    [ValueProvider(typeof(RouteDataValueProviderFactory))] int valueId)
{
    await Task.Delay(5000); // do some async work

    // other logic and return the entity
}

[InvalidateCacheOutput("GetValueEntity")]
[AcceptVerbs("POST")]
[Route("api/values/{valueId}")]
public void UpdateEntity(
    [ValueProvider(typeof(RouteDataValueProviderFactory))] int valueId,
    [FromBody] ValueEntity entity)
{
    // update entity logic
}
```

and given the following sequence of operations:

1. `GET api/values/1` -- not cached, takes ~5s to complete.
2. `GET api/values/1` -- cached, takes ~20ms to complete.
3. `GET api/values/2` -- not cached, takes ~5s to complete.
4. `POST api/values/2` -- updates entity 2, **should invalidate cache entries of ** `api/values/2`
5. `GET api/values/1` -- **should take ~20ms to complete**, _**takes ~5s**_ -- cache entry was invalidated when doing `POST` operation on entity 2.

* This was happening because cache entries of both resources `api/values/1` and `api/values/2` were **sharing the same _baseCacheKey**_ value.
*  Implementing an own `DefaultCacheKeyGenerator` did not help, **as for the _baseCacheKey_** the `MakeCacheKey` method is not called, but this one: `CacheOutputConfiguration.MakeBaseCachekey` -- which is not overridable.

I'm wondering what can be done to achieve my desired behavior.
Can you help? 

Thank you.
Jonathan

**Comment by filipw** [comment]
This is really by design - a POST will invalidate all related GETs on a controller, because interpreting the semantics of action arguments cannot be uniform, and the caching add on should not be opinionated about how things should be laid out on the API surface level.

That said, you can create your invalidate logic based on this https://github.com/filipw/Strathweb.CacheOutput/blob/dev/src/WebApi.OutputCache.V2/InvalidateCacheOutputAttribute.cs#L24 and remove cache according to the pattern that suits you best.

**Comment by johnib** [comment]
Thanks for your response filipw.

Same for invalidation by TTL ? this looks weird - see this [#205](https://github.com/filipw/Strathweb.CacheOutput/issues/215).
